### ISSUE TITLE
Virus avoiding

### ISSUE THREAD

**Issue by DedProtectr** [Apostolique/Stream-Ideas#6]
I think the bot has to avoid viruses from a certain size on. The bot usually grows to big -> runs into virus -> gets split by virus -> gets eaten by player. The bot doesn't get to big before starting over at this rate.

**Comment by Apostolique** [comment]
That was just something that had not been updated after the last Launcher update. Fixed now.

**Comment by DedProtectr** [comment]
Thanks!
